### PR TITLE
Dev session

### PR DESCRIPTION
**Pull request by annguye2**

### CODE REVIEW

**Comment by mark1ad** [comment]
An, could you resolve the conflicts in public/index.html, public/js/app.js, and public/js/users.js?

Also, could you remove:
    models/users.js4ff67a21cc963f09442d721d6272adbf62b4c0fa
    models/users.jsHEAD
     npm-debug.log
    public/index_back.html
    everything in public_AnNguyen

If you could do this before your next push that would be great. Thanks.

**Comment by annguye2** [comment]
I am working on it, almost done

**Comment by annguye2** [comment]
Hi Mark, I don't see the public_AnNguyen at my end,.
Just removed everything that you asked for

**Comment by annguye2** [comment]
Thanks, Mark.   Will do

**Pull request merged**
